name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Display Docker Version
      run: docker --version

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: hornet55/github_actions:${{ github.run_id }}_${{ github.run_attempt }}

    - name: Logout from Docker Hub
      run: docker logout

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
    - name: pull image from docker hub
      run: docker pull hornet55/github_actions:9241658983_2

    - name: Delete old container
      run: docker rm -f reactcontainer

    - name: Run docker container
      run: docker run -d -p 3000:80 --name reactcontainer hornet55/github_actions:9241658983_2
