name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Display Docker Version
      run: docker --version

    - name: Print Environment Variables
      run: printenv

    - name: Check if DOCKER_HUB_USERNAME secret is set
      run: |
        if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
          echo "DOCKER_HUB_USERNAME is not set"
        else
          echo "DOCKER_HUB_USERNAME is set"
        fi

    - name: Print Docker Hub Username
      run: echo "${{ secrets.DOCKER_HUB_USERNAME }}"

    - name: Check if DOCKER_HUB_ACCESS_TOKEN secret is set
      run: |
        if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
          echo "DOCKER_HUB_ACCESS_TOKEN is not set"
        else
          echo "DOCKER_HUB_ACCESS_TOKEN is set"
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:latest

    - name: Logout from Docker Hub
      run: docker logout
