name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Display Docker Version
      run: docker --version

    - name: Manually set Docker Hub Username (Test)
      run: echo "your-docker-hub-username"

    - name: Manually set Docker Hub Access Token (Test)
      run: echo "your-docker-hub-access-token"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: hornet55
        password: dckr_pat_r9vnTvHkkZpKWEuRIvyoTrZoJ4Q

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: your-docker-hub-username/my-image:latest

    - name: Logout from Docker Hub
      run: docker logout
