name: First workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello Harish"
      - name: print good bye
        run: echo "Done- Bye!"


